// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddTradeRequestResourceController from "./add_trade_request_resource_controller"
application.register("add-trade-request-resource", AddTradeRequestResourceController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
